### PR TITLE
rpc/eth: support eth_estimateGas with updated version of oasis-sdk

### LINKED ISSUE #23: support eth_estimateGas with oasis core.EstimateGasForCaller
The current Ethereum gas estimation does not working actually.

Use oasis-sdk `core.EstimateGasForCaller` to estimate gas from [oasis-sdk](https://github.com/oasisprotocol/oasis-sdk/pull/585/)

### PR DESCRIPTION
**Pull request by synote**
Support gas estimation with oasis `EstimateGasForCaller`

Maybe I mistaken the fee structure of oasis Transaction

### CODE REVIEW

**Comment by synote** [comment]
The sdk returns error of `"invalid argument: unexpected type"` in the query.
I wonder if there is anything wrong about the transaction build

**Comment by kostko** [comment]
Are you using the latest runtime build?

**Comment by synote** [comment]
The runtime with latest version of oasis-sdk gives the same result.

**Comment by kostko** [comment]
Please link to the runtime source that you are using.

**Comment by synote** [comment]
the runtime https://github.com/starfishlabs/oasis-evm-paratime/tree/feature/evm-sdk with latest oasis-core

**Comment by kostko** [comment]
This seems to be an issue with serialization of empty slices in Go, should be fixed with https://github.com/oasisprotocol/oasis-sdk/pull/594.

**Comment by ptrus** [comment]
Hey @synote I just tested this and it works now. I have a local branch that I can force-push here, and get it merged

**Comment by ptrus** [comment]
See https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/31 feel free to review that one (i incorporated your changes there)

**Comment by ptrus** [comment]
This was merged into https://github.com/starfishlabs/oasis-evm-web3-gateway/pull/31 thanks Symon!

**Pull request closed without merging**
